### ISSUE TITLE
[Bug]: The setting of folding search results will be reset every time you open obsidian

### ISSUE THREAD

**Issue by Ci9Quester** [Quorafind/Obsidian-Float-Search#60]
### Bug Description

I'm not sure if this is considered a bug or just a default feature of the plugin. After the manual setting failed (failed after restart), I found data.json.
After I use the plugin, it shows as
```
{
  "searchViewState": {
    "query": ""
  },
  "showFilePath": true
}
```
I re-downloaded the plugin and re-opened data.json and it shows as
```
{
  "searchViewState": {
    "query": "",
    "matchingCase": true,
    "explainSearch": false,
    "collapseAll": true,
    "extraContext": false,
    "sortOrder": "alphabetical"
  },
  "showFilePath": false
}
```
But when I set it up through the obsidian internal panel again, it changed back again.
```
{
  "searchViewState": {
    "query": ""
  },
  "showFilePath": true
}
```
Other settings cannot be saved and used

### Obsidian Version

v1.6.3

### Checklist

- [X] I updated to the latest version of the plugin.

**Comment by Quorafind** [comment]
Fixed.

**Comment by churchilldu** [comment]
My plugin and obsidian version is 4.0.0 and 1.7.6 respectively. The issue persist. 
If I set ` collapse results` true, the next time I press Ctrl + F to search,  the `collapse results` is still fase. 
`Show more context` and `Explain search terms` have some problem.
Already tried to reinstall plugin.

**Comment by Quorafind** [comment]
setting of floating search inherits from default search view.

**Comment by churchilldu** [comment]
> setting of floating search inherits from default search view.

1. I didn't install plugin yet. I set collapse results option on default search view true.
2. Then I install plugin. The first time I open floating search the collapse results is false, I set it to true. The next time I open it, it's still false.

![image](https://github.com/user-attachments/assets/9cf7720f-33ba-427a-8279-564202eaa8da)
